# Generated by Django 5.2.4 on 2025-07-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('weekday', models.CharField(max_length=20)),
                ('first_punch', models.TimeField()),
                ('last_punch', models.TimeField()),
                ('total_time', models.DurationField()),
                ('in_temp', models.FloatField()),
                ('out_temp', models.FloatField()),
            ],
        ),
    ]
