# Generated by Django 5.2.4 on 2025-07-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='in_temp',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='out_temp',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='weekday',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='branch',
            field=models.CharField(default='', max_length=100),
        ),
    ]
